name: Auto merge
on:
  pull_request:
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/automerge.yml@1.0.9
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      tfcheck: 'tf-checks-spot-example / Get min/max versions'
