name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  tf-checks-on-demand-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.10
    with:
      working_directory: './examples/on-demand/'
  tf-checks-spot-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.10
    with:
      working_directory: './examples/spot/'



